name: BUILD

on: 
  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    strategy:
      matrix:
        repos: [wps-office, activitywatch-bin, plasma5-wallpapers-dynamic, kwin-scripts-parachute, duf-git, alma, kwin-effects-sliding-notifications, plasma5-applets-virtual-desktop-bar-git, ttf-ms-fonts, gping]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: DuckSoft/build-aur-action@master
      with:
        repo-name: ${{ matrix.repos }}

    - uses: ncipollo/release-action@v1.7.3
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

